apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: employee-app-monitor
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: flask-app
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s