name: CICD

on:
  workflow_dispatch:

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t emp-app:latest -f app/docker/Dockerfile .

      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'emp-app:latest'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: |
          docker tag emp-app:latest ${{ secrets.DOCKER_USERNAME }}/emp-app:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/emp-app:latest